/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/CalendarPage': RouteRecordInfo<'/CalendarPage', '/CalendarPage', Record<never, never>, Record<never, never>>,
    '/DashboardPage': RouteRecordInfo<'/DashboardPage', '/DashboardPage', Record<never, never>, Record<never, never>>,
    '/HomePage': RouteRecordInfo<'/HomePage', '/HomePage', Record<never, never>, Record<never, never>>,
    '/LoginPage': RouteRecordInfo<'/LoginPage', '/LoginPage', Record<never, never>, Record<never, never>>,
    '/MemoryTestPage': RouteRecordInfo<'/MemoryTestPage', '/MemoryTestPage', Record<never, never>, Record<never, never>>,
    '/NotesPage': RouteRecordInfo<'/NotesPage', '/NotesPage', Record<never, never>, Record<never, never>>,
    '/ProfilePage': RouteRecordInfo<'/ProfilePage', '/ProfilePage', Record<never, never>, Record<never, never>>,
    '/SettingsPage': RouteRecordInfo<'/SettingsPage', '/SettingsPage', Record<never, never>, Record<never, never>>,
    '/SignUpPage': RouteRecordInfo<'/SignUpPage', '/SignUpPage', Record<never, never>, Record<never, never>>,
    '/StatisticsPage': RouteRecordInfo<'/StatisticsPage', '/StatisticsPage', Record<never, never>, Record<never, never>>,
    '/SubjectsPage': RouteRecordInfo<'/SubjectsPage', '/SubjectsPage', Record<never, never>, Record<never, never>>,
    '/WrongNotesPage': RouteRecordInfo<'/WrongNotesPage', '/WrongNotesPage', Record<never, never>, Record<never, never>>,
  }
}
